// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0PSY-UtCneW-iuVuxgdrHodddMDCzB0',
    appId: '1:136985135620:web:4f5b513adf7e78de84c351',
    messagingSenderId: '136985135620',
    projectId: 'calculator-ui-698dd',
    authDomain: 'calculator-ui-698dd.firebaseapp.com',
    storageBucket: 'calculator-ui-698dd.firebasestorage.app',
    measurementId: 'G-NNRBTWFSBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXyQegyowLF9kez51nNOX_x9VfF67Jlns',
    appId: '1:136985135620:android:fa6cd7ec18632f9884c351',
    messagingSenderId: '136985135620',
    projectId: 'calculator-ui-698dd',
    storageBucket: 'calculator-ui-698dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuPLHzhTWkYC1J4CFHj-b-K4LLPt67OA0',
    appId: '1:136985135620:ios:1c0357fee53acac884c351',
    messagingSenderId: '136985135620',
    projectId: 'calculator-ui-698dd',
    storageBucket: 'calculator-ui-698dd.firebasestorage.app',
    iosBundleId: 'com.example.calculatorUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuPLHzhTWkYC1J4CFHj-b-K4LLPt67OA0',
    appId: '1:136985135620:ios:1c0357fee53acac884c351',
    messagingSenderId: '136985135620',
    projectId: 'calculator-ui-698dd',
    storageBucket: 'calculator-ui-698dd.firebasestorage.app',
    iosBundleId: 'com.example.calculatorUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl0PSY-UtCneW-iuVuxgdrHodddMDCzB0',
    appId: '1:136985135620:web:6b9541328e8d6faf84c351',
    messagingSenderId: '136985135620',
    projectId: 'calculator-ui-698dd',
    authDomain: 'calculator-ui-698dd.firebaseapp.com',
    storageBucket: 'calculator-ui-698dd.firebasestorage.app',
    measurementId: 'G-4PWXXBFN4Y',
  );
}
